### ISSUE TITLE
git 101 Feature Request - Resources page

### ISSUE THREAD

**Issue by jaywryan** [redhat-adsa/HowWeEnable#15]
You may want to think about "Resources" page for what's next.  I have taught a few git 101 classes and this is one of my favorite resources

https://learngitbranching.js.org/

It's interactive and gets pretty complex.  I'm sure there are lots of other resources to add as well.

**Comment by chadmf** [comment]
WOW that is a fantastic resource doing a PR for it now thanks @jaywryan

**Comment by chadmf** [comment]
fixed in merge #19
